# Generated by Django 3.2 on 2024-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='shade_color',
            field=models.TextField(default=''),
        ),
    ]
