# Generated by Django 3.2 on 2024-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241017_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='6711361bb54730422962c256', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
