# Generated by Django 3.2 on 2024-10-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='6711cf951407dc99c1cf76e7', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
