# Generated by Django 3.2 on 2024-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20241206_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='675404839dd28c75f7756c0f', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
