# Generated by Django 3.2 on 2024-12-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20241207_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='67540a1b55f037449b3a1c40', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
