# Generated by Django 3.2 on 2024-12-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='67540c7b2c1ab05b94720b65', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
