# Generated by Django 3.2 on 2024-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='67599dcbaae5492d856cb104', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
