# Generated by Django 3.2 on 2024-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='6759aae8a29cc12109697f9d', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
