# Generated by Django 3.2 on 2024-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='6759ac809158f4adf577cef5', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
