# Generated by Django 3.2 on 2024-12-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20241211_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='6759cfa5acfa2d706fdeb920', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
