# Generated by Django 3.2 on 2024-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='675b17f892c36d66e84e162a', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
